name = "SoleFeatures"
uuid = "3ceb4e54-d968-4e97-8c18-2deeb0d429fb"
version = "0.3.0"
authors = ["Patrik Cavina", "Federico Manzella", "Giovanni Pagliarini"]

[deps]
DataTreatments = "1b3ff5f2-9b56-42a2-b38a-76a033f741ca"

[compat]
DataTreatments = "0.3"
julia = "1"

[sources]
DataTreatments = {rev = "devMethods", url = "https://github.com/PasoStudio73/DataTreatments.jl.git"}
