name = "SoleFeatures"
uuid = "3ceb4e54-d968-4e97-8c18-2deeb0d429fb"
authors = ["Eduard I. STAN", "Giovanni PAGLIARINI"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
